# Generated by Django 2.0.7 on 2018-08-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='instrumentos'),
        ),
    ]
