# Generated by Django 2.0.7 on 2018-08-23 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_instrumento_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='foto',
        ),
    ]
