# Generated by Django 2.0.7 on 2018-08-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_instrumento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='precio',
            field=models.CharField(max_length=13),
        ),
    ]
