# Generated by Django 2.0.7 on 2018-08-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180828_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles'),
        ),
    ]
