# Generated by Django 2.0.7 on 2018-08-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_instrumento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='instrumentos'),
        ),
    ]
