# Generated by Django 2.0.7 on 2018-08-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180830_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='foto',
            field=models.ImageField(blank=True, default='congas.jpg', null=True, upload_to='instrumentos'),
        ),
    ]
