# Generated by Django 2.0.7 on 2018-08-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180830_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='foto',
            field=models.ImageField(blank=True, default='instrumentos/const.png', null=True, upload_to='instrumentos'),
        ),
    ]
